// SMS:autogenerated_begin
#include "def.h"
#include "sacl.h"

template <>
void sacl<Tpf::sacl::def>()
{
}
namespace Tpf
{
// SMS:autogenerated_end
// SMS:autogenerated_begin
}
// SMS:autogenerated_end
