// SMS:autogenerated_begin
#pragma once
#include "./tpf.h"
namespace Tpf
{
    namespace sacl { struct Id; }
// SMS:autogenerated_end

    struct Id;


    template <
        typename T
    >
    struct tpf<Id, T>
    {
        using type = T;
    };


// SMS:autogenerated_begin
}
// SMS:autogenerated_end
