// SMS:autogenerated_begin
#include "Prepend.h"
#include "sacl.h"

template <>
void sacl<Tpf::sacl::Prepend>()
{
}
namespace Tpf
{
// SMS:autogenerated_end
// SMS:autogenerated_begin
}
// SMS:autogenerated_end
