// SMS:autogenerated_begin
#pragma once
#include "tpf.h"
#include "Id.h"
namespace Tpf
{
    namespace sacl { struct return_; }
// SMS:autogenerated_end

    template <
        typename... Def
    >
    using return_ = apply<apply<Def...>, Id>;


// SMS:autogenerated_begin
}
// SMS:autogenerated_end
