// SMS:autogenerated_begin
#include "tpf.h"
#include "sacl.h"

template <>
void sacl<Tpf::sacl::tpf>()
{
}
namespace Tpf
{
// SMS:autogenerated_end
// SMS:autogenerated_begin
}
// SMS:autogenerated_end
