#pragma once
#include "tpf.h"
namespace Tpf
{
    namespace sacl { struct Tuplify; }

    struct Tuplify;


    template <
        typename... Ts
    >
    struct tpf<Tuplify, Ts...>
    {
        using type = std::tuple<Ts...>;
    };

// SMS:autogenerated_begin
}
// SMS:autogenerated_end
