#include <iostream>
#include <type_traits>
#include <tuple>

using std::true_type;
using std::false_type;
using std::size_t;
using std::begin;
using std::rbegin;
using std::end;
using std::rend;
using std::move;
using std::forward;
using std::initializer_list;
using std::tuple;
using std::array;
using std::get;
using std::is_same;
using std::conjunction;
using std::conjunction_v;
using std::conditional;
using std::conditional_t;
using std::enable_if;
using std::string;
using std::cout;
using std::cerr;
using std::endl;
using std::ostream;
