# vim: et ts=2 sw=2

module ComponentSourceDetails
  @mod_name : String
  @comp_name : String
  include ConfDirViews  # conf_*
  include SourceDetails  # polymorphic inheritance
  include Sagas

  def mod_name
    @mod_name
  end

  def comp_name
    @comp_name
  end

  def path
    File.join(
      conf_sms_root,
      conf_project_root,
      "src",
      @mod_name,
      "#{@comp_name}.cpp"
    )
  end

  def saga_define_sacl
    [
      (saga_line { "template <>" }),
      (saga_line { "void sacl<#{@mod_name}::sacl::#{@comp_name}>()" }),
    ] +
    saga_empty_body
  end

  def saga_open_modspace
    [
      (saga_line { "namespace #{@mod_name}" }),
      (saga_line { "{" }),
    ]
  end

  def file_header_saga
    saga_warn_autogenerated_begin +
      saga_include_header(@comp_name) +
      saga_include_header("sacl") +
      saga_empty_line +
      saga_define_sacl +
      saga_open_modspace +
      saga_warn_autogenerated_end
  end

  def file_footer_saga
    saga_warn_autogenerated_begin +
      saga_close_modspace +
      saga_warn_autogenerated_end
  end
end
