# vim: et ts=2 sw=2

module Source
  @mod_name : String
  @comp_name : String
  include ConfDirViews
  include FileViews

  def warn_autogenerated_begin
    [1]
  end

  def warn_autogenerated_end
    [1]
  end

  def include_header
    [1]
  end

  def include_sacl
    [1]
  end

  def empty_line
    [1]
  end

  def define_sacl
    [1, 1, 1, 1]
  end

  def header_saga
    warn_autogenerated_begin +
      include_header +
      include_sacl +
      empty_line +
      define_sacl +
      warn_autogenerated_end
  end

  def header_generated_lines_count
    header_saga.size
  end
end
