// SMS:autogenerated_begin
#include "Id.h"
#include "sacl.h"

template <>
void sacl<Tpf::sacl::Id>()
{
}
namespace Tpf
{
// SMS:autogenerated_end
// SMS:autogenerated_begin
}
// SMS:autogenerated_end
