// SMS:autogenerated_begin
#include "return_.h"
#include "sacl.h"

template <>
void sacl<Tpf::sacl::return_>()
{
}
namespace Tpf
{
// SMS:autogenerated_end
// SMS:autogenerated_begin
}
// SMS:autogenerated_end
