// SMS:autogenerated_begin
#include "Tpf.h"
#include "sacl.h"

template <>
void sacl<Tpf::sacl::sacl_mod>()
{
    sacls<TPF__SACLS>();
}
namespace Tpf
{
// SMS:autogenerated_end
// SMS:autogenerated_begin
}
// SMS:autogenerated_end
