// SMS:autogenerated_begin
#pragma once
#include "Tpf/Append.h"
#include "Tpf/Id.h"
#include "Tpf/Prepend.h"
#include "Tpf/return_.h"
#include "Tpf/tpf.h"
#include "Tpf/Tuplify.h"
namespace Tpf
{
    namespace sacl { struct sacl_mod; }
// SMS:autogenerated_end
// SMS:autogenerated_begin
}
// SMS:autogenerated_end
